-- Staff table for school ERP
CREATE TABLE staff (
    staff_id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    gender VARCHAR(10),
    dob DATE,
    marital_status VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(20),
    current_address VARCHAR(255),
    permanent_address VARCHAR(255),
    emergency_contact_person VARCHAR(100),
    emergency_contact_number VARCHAR(20),
    department VARCHAR(100),
    role_designation VARCHAR(100),
    areas_of_expertise VARCHAR(255),
    education_qualifications TEXT,
    research_interests TEXT,
    previous_experience TEXT,
    publications TEXT,
    certifications TEXT,
    courses_handled TEXT,
    date_of_joining DATE,
    employee_id VARCHAR(50) UNIQUE,
    employment_type VARCHAR(30),
    salary_ctc DECIMAL(12,2),
    grade_pay VARCHAR(20),
    bank_account_details VARCHAR(100),
    pan_number VARCHAR(20),
    aadhaar_number VARCHAR(20),
    photo_url VARCHAR(255),
    digital_signature_url VARCHAR(255),
    achievements_awards TEXT,
    languages_known VARCHAR(100),
    mentoring_availability VARCHAR(50),
    linkedin_profile VARCHAR(255),
    researchgate_profile VARCHAR(255),
    google_scholar_profile VARCHAR(255),
    special_roles VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
