// User Role Constants
export const ROLES = {
  PRINCIPAL: 'PRINCIPAL',
  FACULTY: 'FACULTY',
  WARDEN: 'WARDEN',
  HOSTEL_INCHARGE: 'HOSTEL_INCHARGE',
  STUDENT: 'STUDENT'
};

// Permission definitions for each module
export const PERMISSIONS = {
  DASHBOARD: 'dashboard',
  STUDENTS: {
    VIEW: 'students:view',
    MANAGE: 'students:manage',
    ATTENDANCE: 'students:attendance'
  },
  TEACHERS: {
    VIEW: 'teachers:view',
    MANAGE: 'teachers:manage',
    ATTENDANCE: 'teachers:attendance'
  },
  HOSTEL: {
    VIEW: 'hostel:view',
    MANAGE: 'hostel:manage',
    ROOM_ALLOCATION: 'hostel:room_allocation',
    COMPLAINTS: 'hostel:complaints'
  },
  FEES: {
    VIEW: 'fees:view',
    MANAGE: 'fees:manage',
    APPROVE: 'fees:approve'
  },
  LIBRARY: {
    VIEW: 'library:view',
    MANAGE: 'library:manage',
    ISSUE_BOOKS: 'library:issue_books'
  },
  TRANSPORT: {
    VIEW: 'transport:view',
    MANAGE: 'transport:manage'
  },
  REPORTS: {
    VIEW: 'reports:view',
    GENERATE: 'reports:generate'
  },
  MESSAGES: {
    VIEW: 'messages:view',
    SEND: 'messages:send',
    MANAGE: 'messages:manage'
  }
};

// Role-based permission mappings
export const ROLE_PERMISSIONS = {
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.STUDENTS.VIEW,
    PERMISSIONS.STUDENTS.MANAGE,
    PERMISSIONS.TEACHERS.VIEW,
    PERMISSIONS.TEACHERS.MANAGE,
    PERMISSIONS.HOSTEL.VIEW,
    PERMISSIONS.HOSTEL.MANAGE,
    PERMISSIONS.FEES.VIEW,
    PERMISSIONS.FEES.MANAGE,
    PERMISSIONS.FEES.APPROVE,
    PERMISSIONS.LIBRARY.VIEW,
    PERMISSIONS.TRANSPORT.VIEW,
    PERMISSIONS.TRANSPORT.MANAGE,
    PERMISSIONS.REPORTS.VIEW,
    PERMISSIONS.REPORTS.GENERATE,
    PERMISSIONS.MESSAGES.VIEW,
    PERMISSIONS.MESSAGES.SEND,
    PERMISSIONS.MESSAGES.MANAGE
  ],
  
  [ROLES.FACULTY]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.STUDENTS.VIEW,
    PERMISSIONS.STUDENTS.ATTENDANCE,
    PERMISSIONS.LIBRARY.VIEW,
    PERMISSIONS.MESSAGES.VIEW,
    PERMISSIONS.MESSAGES.SEND,
    PERMISSIONS.REPORTS.VIEW
  ],

  [ROLES.WARDEN]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.HOSTEL.VIEW,
    PERMISSIONS.HOSTEL.MANAGE,
    PERMISSIONS.HOSTEL.ROOM_ALLOCATION,
    PERMISSIONS.HOSTEL.COMPLAINTS,
    PERMISSIONS.STUDENTS.VIEW,
    PERMISSIONS.MESSAGES.VIEW,
    PERMISSIONS.MESSAGES.SEND
  ],

  [ROLES.HOSTEL_INCHARGE]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.HOSTEL.VIEW,
    PERMISSIONS.HOSTEL.ROOM_ALLOCATION,
    PERMISSIONS.HOSTEL.COMPLAINTS,
    PERMISSIONS.STUDENTS.VIEW,
    PERMISSIONS.MESSAGES.VIEW,
    PERMISSIONS.MESSAGES.SEND
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.FEES.VIEW,
    PERMISSIONS.LIBRARY.VIEW,
    PERMISSIONS.HOSTEL.VIEW,
    PERMISSIONS.HOSTEL.COMPLAINTS,
    PERMISSIONS.MESSAGES.VIEW,
    PERMISSIONS.MESSAGES.SEND
  ]
};